/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

public class GitHubGreeter {

  // Write the welcome method here
    public String welcome(String name) {
        name = "Quinn";
        return "Welcome to GitHub, " + name;
    }
    public String wishes() {
        return "Have a great semester in CSC 241!";
    }
  // Write the wishes method here

}
